#! /bin/bash -x

echo "---------------------------------------------------------------------Welcome To FILP Coin Simulator------------------------------------------------------------------------------------"

#HEADS AND TAILS ARE GIVEN VALUES 1 AND 0 REPECTIVELY
HEADS=1
TAILS=0
HEADS_WIN_COUNTER=0
TAILS_WIN_COUNTER=0
STOP_FLIPPING=0
#CHECKING IF HEAD WON OR TAIL WON

#SIMULATES COIN FILP UNTIL ONE GETS TO 21
function CoinFlip(){
	coinSaid=$((RANDOM%2))
	if [ $coinSaid == $HEADS ]
	then
		((HEADS_WIN_COUNTER++))
		echo "HEADS WON!!!!!!"
	else
		((TAILS_WIN_COUNTER++))
		echo "TAILS WON!!!!!!"
	fi
}

#CODE BELOW DISPLAYS OUTPUT
while [ $STOP_FLIPPING != 1 ]
do
CoinFlip
if [ $HEADS_WIN_COUNTER == 21 ]
then
	CoinFlip
#HERE WE CHECK IF IT'S A TIE THEN WE FLIP TILL SOMEBODY REACHES 2 POINTS AHEAD THAN THE OTHER
	if [ $TAILS_WIN_COUNTER == 21 ]
	then
		echo  "(((IT'S A TIE)))"
		while [ $STOP_FLIPPING != 1 ]
			do
			CoinFlip
			if [ $(($HEADS_WIN_COUNTER-$TAILS_WIN_COUNTER)) == 2 ] || [ $(($TAILS_WIN_COUNTER-$HEADS_WIN_COUNTER)) == 2 ]
			then
				STOP_FLIPPING=1
				if [ $TAILS_WIN_COUNTER > $HEADS_WIN_COUNTER ]
            then echo "TAILS WON BY $(($TAILS_WIN_COUNTER-$HEADS_WIN_COUNTER)) MORE WINS THAN HEADS"
            	echo  "TAILS WON $TAILS_WIN_COUNTER TIMES AND HEADS WON $HEADS_WIN_COUNTER TIMES"
            else echo "HEADS WON BY $(($HEADS_WIN_COUNTER-$TAILS_WIN_COUNTER)) MORE WINS THAN TAILS "
            	echo "HEADS WON $HEADS_WIN_COUNTER TIMES AND TAILS WON $TAILS_WIN_COUNTER TIMES"
            fi
			fi
		done
	else
	STOP_FLIPPING=1
	echo "HEADS WON BY $(($HEADS_WIN_COUNTER-$TAILS_WIN_COUNTER-1)) MORE WINS THAN TAILS "
	echo "HEADS WON $(($HEADS_WIN_COUNTER-1)) TIMES AND TAILS WON $TAILS_WIN_COUNTER TIMES"
	fi
else
	if [ $TAILS_WIN_COUNTER == 21 ]
	then
		CoinFlip
		if [ $HEADS_WIN_COUNTER == 21 ]
		then
			echo "(((IT'S A TIE)))"
			while [ $STOP_FLIPPING != 1 ]
			do
			CoinFlip
			if [ $(($HEADS_WIN_COUNTER-$TAILS_WIN_COUNTER)) == 2  ] || [ $(($TAILS_WIN_COUNTER-$HEADS_WIN_COUNTER)) == 2 ]
				then
				STOP_FLIPPING=1
				if [ $HEADS_WIN_COUNTER > $TAILS_WIN_COUNTER ]
				then echo "TAILS WON BY $(($TAILS_WIN_COUNTER-$HEADS_WIN_COUNTER)) MORE WINS THAN HEADS"
				echo  "TAILS WON $TAILS_WIN_COUNTER TIMES AND HEADS WON $HEADS_WIN_COUNTER TIMES"
				else echo "HEADS WON BY $(($HEADS_WIN_COUNTER-$TAILS_WIN_COUNTER)) MORE WINS THAN TAILS "
		             	echo "HEADS WON $HEADS_WIN_COUNTER TIMES AND TAILS WON $TAILS_WIN_COUNTER TIMES"
				fi
			fi
			done
	else
	STOP_FLIPPING=1
	echo "TAILS WON BY $(($TAILS_WIN_COUNTER-$HEADS_WIN_COUNTER-1)) MORE WINS THAN HEADS"
	echo "TAILS WON $(($TAILS_WIN_COUNTER-1)) TIMES AND HEADS WON $HEADS_WIN_COUNTER TIMES"
		fi
	fi
fi
done
